### ISSUE TITLE
APP端 长时间会自动退出

### ISSUE THREAD

**Issue by panxinkai** [szvone/Vmq#10]
上次说过了,MIUI系统在系统休眠后APP端半小时才发一次心跳 但是不影响使用,但是长时间这样的话 微信和支付宝也会休眠收不到收款信息所以导致回调失败.但是监控端不会退出会一直在后台运行
所以最近一直24H亮屏,这样心跳正常回调也正常,但是APP会在3个小时左右就会自动退出,网页端显示APP端掉线,打开程序发现已经关掉了(屏幕常开,停留在APP界面也一样),得重新运行点击开启服务才正常,这就很苦恼了,无法正常使用了..
以上问题跟系统设置无关,不管是开发者模式充电时屏幕不休眠,还是直接不锁屏停留在APP界面是一样的,都是时间长就会自动关闭,不知为何.,
以上测试机型为红米2A(5.1.1), 360n6(7.1.1)都不行!都会自动退出!获取推送不知道是主动还是被动,没找到延迟的地方,本来想改下延迟在测试下,找不到也没改.

总结就是该系统还是无法长时间稳定运行,锁屏后推送不及时,不锁屏就会退出 测试了2天得出的结果!

**Comment by gabrielxvx** [comment]
确实，熄屏后程序就被冻结了一样(已加白名单，无限制，无省电模式)。我加了一段计时器，发现熄屏后程序并未退出，而是冻结了一样，计时器也不在计时，点亮屏幕计时器继续计时。搞不懂是为什么，希望作者能将其注册为服务，这样应该可以保持后台一直运行。

**Comment by szvone** [comment]
问题是我已经注册成服务了

**Comment by gabrielxvx** [comment]
笨办法,可以实现熄屏后正常心跳
// 获取电源锁，保持该服务在屏幕熄灭时仍然获取CPU时，保持运行
 private void acquireWakeLock() {
  if (null == wakeLock) {
   PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
   wakeLock = pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK
     | PowerManager.ON_AFTER_RELEASE, getClass()
     .getCanonicalName());
   if (null != wakeLock) {
    wakeLock.acquire();
   }
  }
 }

 // 释放设备电源锁
 private void releaseWakeLock() {
  if (null != wakeLock && wakeLock.isHeld()) {
   Log.i(TAG, "call releaseWakeLock");
   wakeLock.release();
   wakeLock = null;
  }
 }

**Comment by szvone** [comment]
App已经更新，请下载新版使用
