### ISSUE TITLE
代码读取部分二维码时抛异常：com.google.zxing.NotFoundException

### ISSUE THREAD

**Issue by wushuaihua520** [szvone/Vmq#20]
在配置微信和支付宝二维码时，微信二维码基本能成功上传并识别；
但支付宝二维码就得看运气了，时常上传失败或不能正确读取内容。

由于我初转java，以前是.NET，所以也只能百度。幸运的是，问题成功解决。
下面贴上代码，大神轻喷，多多交流。

代码如下：

```
//优化精度
hints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);

//复杂模式
hints.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
```

![微信截图_20191219220518](https://user-images.githubusercontent.com/17560218/71179852-eed65f80-22ab-11ea-8098-f4e606a3c575.png)

**Comment by ybyaoyao** [comment]
老兄，请教一下你是怎么修改的呢

**Comment by wushuaihua520** [comment]
> 老兄，请教一下你是怎么修改的呢

识别二维码之前，加上我上面贴的那两句代码
