### ISSUE TITLE
j监控端以开启，为什么查询服务端却显示监控端没有绑定？

### ISSUE THREAD

**Issue by heihei180** [szvone/Vmq#3]
`{"code":1,"msg":"成功","data":{"lastpay":"0","lastheart":"0","state":"-1"}}`

监控端检测服务状态显示：程序运行正常

**Comment by szvone** [comment]
监控端服务状态检测只是检测是否正常开启辅助功能，近期修复

**Comment by szvone** [comment]
问题已修复，请下载最新版
