### ISSUE TITLE
金额整数会提示签名错误

### ISSUE THREAD

**Issue by panxinkai** [szvone/Vmq#4]
100或者100.00都会，会提示签名错误，还有这个没数据库那那些订单如何删除？如何迁移数据呢？

**Comment by szvone** [comment]
金额整数已经修复，请下载最新版本
有数据库，使用的是h2数据库，数据库文件位于用户目录下的mq.mv.db
window位于：C:\Users\用户名\mq.mv.db
linux应该位于：~/mq.mv.db
