### ISSUE TITLE
总结下BUG

### ISSUE THREAD

**Issue by panxinkai** [szvone/Vmq#6]
大神你好,很喜欢你写的东西,也一直在用,但是有几个BUG总结下,希望能改进下.
1:金额问题 金额为整时会签名错误 比如 100 100.00 200 200.00 199 199.00 等 必须是小数点后面有数字才行
2:回调问题,不知道为什么老是回调显示通知失败,success也写了就是不行,会返回乱码,可能是GBK格式的事
3:心跳包能不能设置长一些,我的MIUI8系统锁屏后通知会自动获取但是V免签APP半小时才发送一次心跳包,但是不影响使用,后台会显示监控掉线,我看了源码是超过1分钟就显示掉线,能不能调长一些,(java编译不了,不知道为什么 老提示错误.)
4:支付宝的个人收款和商家收款通知推送内容不一样,v免签只能获取个人的,商家的获取不了
5:看源码好像是1分钟清理一次过期订单,但是后台的订单列表还是那些也没法删除,能加个按钮好了
还有大神能不能写个简单的PHP回调处理,好学习一下
别的暂时没发现就这么多了,不知道为什么用eclipse编译不了源码老提示错误,奈何小白一个解决不了,

**Comment by szvone** [comment]
首先感谢您的反馈，下面针对您的问题提出回答

1、该问题在V1.2版本已经修复
2、该问题将会在近期修复
3、心跳包时间设置成1分钟是为了监控掉线状态，MIUI系统请在设置->电量和性能->应用配置->V免签监控端，在此界面将后台配置设置成无限制即可
4、麻烦贴上商家的推送内容，我将在下一次更新增加商家收款支持
5、系统是一分钟一次将过期的订单标记为过期状态，针对无效订单清理问题将会在下个版本加入
6、回调处理有空我会贴上
7、该项目是IDEA项目，在eclipse我也不知道怎么用

**Comment by szvone** [comment]
问题4已修复

**Comment by szvone** [comment]
问题2 问题5 已经更新 php回调示例已经增加，所有反馈均处理完成
