### ISSUE TITLE
IDEA打包成war 本地测试提示 Error: Could not find or load main class ${start-class}

### ISSUE THREAD

**Issue by greezi** [szvone/Vmq#7]
测试打包成war
执行 `java -jar mq_war.war`
提示找不到主类
`Error: Could not find or load main class ${start-class}`

请问这是什么情况呢？

**Comment by szvone** [comment]
可能是mavan配置有问题，我这边编译是正常的，这边有两个资料可以参考下 也可以google更多的资料
https://blog.csdn.net/moshowgame/article/details/81626844
https://blog.csdn.net/blueheart20/article/details/52185440
