### ISSUE TITLE
后台管理首页的订单统计三个无效的

### ISSUE THREAD

**Issue by panxinkai** [szvone/Vmq#8]
大神你好
首页的 今日失败订单 今日收入 总收入 总是0不计数
还有回调问题 确实是格式的事,不能用GBK或UTF-8,只能用ANSI否则会返回乱码
研究半天才发现,用记事本打开另存为编码选择ANSI调试就正常了

还有就是这个通知失败后会自动补单吗?多久一次呢

**Comment by panxinkai** [comment]
不好意思,是两个不管用,今日失败那个管用,就是今日收入和总收入不管用
还有就是我觉得APP端心跳还是太快了 几秒钟一个我觉得快了点
能加个日志功能就好了 这样就完美了

**Comment by panxinkai** [comment]
因为小米手机确实是有一些问题 不管是神隐模式设置如何也是通知不到位.所以换了360 n6手机
系统是7.1.1,但是无法使用,首先是扫码就闪退,手动输入配置后心跳正常但是无法获取到通知
可能是通知栏有个设置叫 通知使用权 这个设置很多手机都有,大概意思就是获取所有应用通知的权限,
但是里面没有v免签所以无法打开,所以获取不到任何的通知 导致失效,希望能加上这个基本就通用了

**Comment by panxinkai** [comment]
这个订单统计是有一些问题的，0点以后还是显示昨天的，应该要重启才可以吧，没测试。
还有app能加个唤醒功能吗 这样后台就可以正常心跳了，因为手机要是锁屏后cpu也会休眠，时间长会深度休眠 ，收款通知无法回调，不锁屏一直亮屏也不太现实，我现在是用系统自带音乐旋环播放歌曲声音调最低，这样可以避免cpu休眠，心跳回调就一直正常了，要是app能自带就好了。类似于只关屏，不休眠这种。不知道你知道我说的什么没，说的有点乱。

**Comment by szvone** [comment]
感谢反馈，新版已经修复，请下载使用
