### ISSUE TITLE
扫码付款成功不返回通知

### ISSUE THREAD

**Issue by gabrielxvx** [szvone/Vmq#9]
手机端开启监控，心跳正常。扫码付款成功后，没反应，没有跳转。安卓6.0。

**Comment by panxinkai** [comment]
是的,我测试的有安卓5.1.1通知,7.1.1 就不通知了

**Comment by szvone** [comment]
收到款后是否有推送，我测试是正常的，6.0 miui10

**Comment by szvone** [comment]
https://jingyan.baidu.com/article/36d6ed1fb0f25c1bcf4883b8.html
尝试参考此教程看是否能解决，开启 通知使用权 这个权限

**Comment by panxinkai** [comment]
不管用的，通知使用权我知道在哪，但是里面没有v免签

**Comment by zcc71** [comment]
VIVO X9 不知道哪里设置通知使用权， 有知道的吗

**Comment by gabrielxvx** [comment]
已解决，微信版本的问题。

**Comment by leohuangyy** [comment]
微信版本是要使用哪个版本才可以呢？
